# Generated by Django 5.2.4 on 2025-07-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='aplied_at',
            new_name='applied_at',
        ),
    ]
